---
title: "Math Problem Set 1"
author: "Tim Munday"
output: pdf_document
---

```{r setup, include=FALSE}
{
knitr::opts_chunk$set(echo = TRUE)

  rm(list = ls())
  
  Sys.setenv(JAVA_HOME="C:\\Program Files (x86)\\Java\\jre1.8.0_144")
  if(!require(rJava)){
    install.packages('rJava')
    library(rJava)
  }
}
  
```  

#Section one answers

\textbf{Ex 1.3}

\setlength{\leftskip}{10pt}

G1 - Since G1 only includes open sets, it is not closed under complements and finite unions (since the complements of open sets are necessarily closed), and so cannot be an algebra.

G2 - G2 is an algebra, but not a $\sigma$-algebra. It fulfils the two requirements of containing the empty set and being closed under complements and finite unions that are needed to be an algebra. However, since the unions are not countable G2 is not a $\sigma$-algebra.

G3 - G3 is a $\sigma$-algebra. It passes both requirements: containing the empty set and is closed under countable unions.

\setlength{\leftskip}{0pt}

\textbf{Ex 1.7}

\setlength{\leftskip}{10pt}

\textbf{Part a} \newline
We know that both examples are $\sigma$-algebras. Both contain the empty set (by definition), and are closed under countable unions.
Then since $P(X)$ is the largest set such that all members are in $X$, it must be the largest $\sigma$-algebra.


\textbf{Part b}  \newline
The first condition for a $\sigma$-algebra is that $\emptyset$ is a member.The second condition is that a $\sigma$-algebra must be closed under complements. Thus if it contains $\emptyset$ it must also contain $X$ at a minimum. Therefore the smallest $\sigma$-algebra is $\{\emptyset, X \}$.

\setlength{\leftskip}{0pt}

\textbf{Ex 1.10}

  \setlength{\leftskip}{10pt}

\textbf{Condition 1} \newline
If $\emptyset$ is in all $S_\alpha$ then it is also in the intersection of the $S_\alpha$, i.e. it is contained within $\bigcap_\alpha S_\alpha$.

\textbf{Condition 2} \newline
Suppose $A \in \bigcap_\alpha S_\alpha$ then clearly $A$ is in all $S_\alpha$. Since all the $S_\alpha$ are closed under complements (as they are $\sigma$-algebras), then $A^c$ is in all $S_\alpha$ and so is also in the intersection of the $S_\alpha$. Therefore the intersection of the $S_\alpha$ is closed under complements, so the second condition is satisfied.

  \setlength{\leftskip}{0pt}

\textbf{Ex 1.17}

  \setlength{\leftskip}{10pt}

\textbf{Prove monotonicity} \newline
We want to prove $\mu$ is montone. i.e. if $A, B \in S, A \subset B$ then $\mu(A) \leqslant \mu(B)$

Let us define $Y = B \cap A^c$
We know that $Y \in S$
$\mu(Y \cap A) = \mu(A) + \mu(Y)$ as $A$ and $Y$ are disjoint
$\mu(B) = \mu(A \cap B) + \mu(Y)$
$=\mu(A) + \mu(Y)$
Since $\mu(Y) \geqslant 0$
Then $\mu(A) \leqslant \mu(B)$
So the proposition is proved

\textbf{Prove countable subadditivity} \newline
Define a sequence of new sets: $B_1 = A_1$, $B_2 = A_2 - A_1$, $B_3 = A_3 - (A_1 \cup A_2)$ and so on and so forth.
Then we notice that $\cup_{n}A_n = \cup_{n} B_n$
We have already proved monotonicity, therefore we know that $\mu(B_n) \leqslant \mu(A_n)$ for all $n$. Summing over n we get the result that $\mu(\cup_{n} A_n) \leqslant \Sigma_{n}\mu(A_n)$

  \setlength{\leftskip}{0pt}

\textbf{Ex 1.18}

  \setlength{\leftskip}{10pt}
  
There are two conditions for a measure, that it assigns zero to the empty set, and that the measure of the union of a collection of sets is equal to the sum of the measures of those sets, if the sets are disjoint.

\textbf{Condition 1} \newline
$\lambda(\emptyset) = \mu(\emptyset \cap B)$
$= \mu(\emptyset)$
$=0$

\textbf{Condition 2} \newline
$lambda(\cup_{i}^{\infty} A_i) = \mu(\cup_{i}^{\infty} A_i \cap B)$
If the $A$'s are disjoint, then so are their intersections with B. So defining $Y_i = A_i \cap B$ we can write:
$\mu(\cup_{i}^{\infty}) = \Sigma \mu(Y_i)$
$=\Sigma \mu(A_i \cap B)$

  \setlength{\leftskip}{0pt}

\textbf{Ex 1.20}

  \setlength{\leftskip}{10pt}

We realise that because we have a decreasing sequence of sets, $A_1 - A_n$ gets larger as n grows.

We can then use the result for increasing sets that is in the notes to construct the proof for decreasing sets.

$\mu(\cap_{i=1}^\infty A_i) = \mu[A_1 - \cup_{i=1}^\infty (A_1 - A_i) ]$
$= \mu(A_1) - \mu[\cup_{i=1}^\infty (A_1 - A_n)]$
$= \mu(A_1) - \lim_{n \to \infty} \mu(A_1 - A_n) = \mu(A_1) - \lim_{n \to \infty} [\mu(A_1) - \mu(A_n)]$
$= \lim_{n \to \infty} \mu(A_n)$

  \setlength{\leftskip}{0pt}

# Section 2 answers

\textbf{Ex 2.10}

  \setlength{\leftskip}{10pt}

We know that since $\mu^*$ is an outer-measure, it is countably subadditive. i.e. $\mu^{*}(\cup_{i}^{\infty}A_i) \leqslant \Sigma_{i} \mu^{*}(A_i)$
To prove the statement we can show that the $\geqslant$ in Theorem 2.8 can be replaced by a $\leqslant$.

Rewriting the statement regarding countable subadditivity gives:
$\mu^{*}(\cup\{B\cap E, B\cap E^{c}\}) \leqslant \mu^{*}(B \cap E) + \mu^{*}(B \cap E^{c})$
By the defintion of B we can say that the left hand side equals $\mu^{*}(B)$
Thus we have shown that the $\geqslant$ in Theorem 2.8 can be replaced by a $\leqslant$ and the proposition is proved.

  \setlength{\leftskip}{0pt}

\textbf{Ex 2.14}

  \setlength{\leftskip}{10pt}

We define $\cal{O}$ as all the open sets in $\mathbb{R}$. Define $v$ as the premeasure on $\mathbb{R}$. $\mu^*$ is the outer measure on $\mathbb{R}$ generated by $v$. Denote $\sigma(\cal{O})$ as the $\sigma$-algebra generated by $\cal{O}$. Then we can use Theorem 2.12, to say that $\sigma(\cal{O})$ is contained within the $\sigma$-algebra generated by the Caratheodory construction. Since $\sigma(\cal{O})$ is the $\sigma$-algebra generated by $\cal{O}$, it is the Borel sigma field, so we have proved the statement.

  \setlength{\leftskip}{0pt}


# Section 3 answers

\textbf{Ex 3.1}

  \setlength{\leftskip}{10pt}

The subset we want the measure of is countable, so let us define it as $X = \{ x_1, x_2, ...\}$ where $x_i$ are subsets of the real line.

Then let us define a cover of this set:

$Cover = \{x_i - \frac{\epsilon}{2^i}, x_i + \frac{\epsilon}{2^i}\}$

The total length of this cover (by taking an infinite sum) is $2\epsilon$

Therefore we can pick $\epsilon$ low enough such that the measure of $X$ is zero.

  \setlength{\leftskip}{0pt}

\textbf{Ex 3.4}

  \setlength{\leftskip}{10pt}

We want to explain how $\{ x \in X : f(x) < a\}$ can be replaced by any of three other conditions:
$1. \{ x \in X : f(x) \leqslant a\}$
$2. \{ x \in X : f(x) > a\}$ 
$3. \{ x \in X : f(x) \geqslant a\}$ 

Proving 3:
$M$ is the $\sigma$-algebra generated by $X$. Since $\sigma$-algebra's are closed under complements, then if the sets such that $f(x) < a$ are in M, then the sets such that $f(x) \geqslant a$ must also be in M. Thus we can replace the original condition by condition 3.

Proving 2:
Lets create a sequence $\{a_n\}$ where the limit is $a$.
We know that $A_n = {x \in X : f \geqslant  a_n}$ is in $M$ from the above proof. We also know that $M$ is closed under contable unions, and since all $A_n$ are in M, we can write: $\cup_{i}^\infty A_n \in M$. And since $a$ is the limit of the sequence $\{a_n\}$, we can also write this as
$\{ x \in X: f(x) > a\}$.

Proving 1: Using the same argument we used for 3, on 2, we can prove 1.

  \setlength{\leftskip}{0pt}

\textbf{Ex 3.7}

  \setlength{\leftskip}{10pt}

$f+g$ and $f*g$ are both continuous functions, therefore property 4 implies that they are measurable functions.
If a maximum exists for $(f, g)$ then it is the supremum (and vice versa for the infimum), therefore property 2 implies that $max(f, g)$ and $min(f, g)$ are measurable.
Finally $|f|$ can be rewritten as the continous function: $F = (f(x)^2)^{0.5}$ thus we can use property 4 to prove this is also measurable.

  \setlength{\leftskip}{0pt}
  
# Section 4 answers

(worked with Cache and Alberto on these answers)

\textbf{Exercise 4.13:}

  \setlength{\leftskip}{10pt}

Since $0\leq||f||<M$, we can apply Proposition $4.5$ to obtain
$0\le\int_E||f||d\mu\le M\mu(E)<\infty$.
Therefore $f\in\mathcal L^1(\mu, E)$.

  \setlength{\leftskip}{0pt}

\textbf{Exercise 4.14:}

  \setlength{\leftskip}{10pt}

Proof by contrapositive.
Suppose there exists a measurable set $E'\subset E$ 
with positive $\mu-$measure such that $f(E')=\{\infty\}$
(we consider just $\infty$ without loss of generality).
Then $\infty=\int_{E'}fd\mu\leq\int_Efd\mu\leq\int_E||f||d\mu$
(the proof of the first inequality can be found in the proof of Exercise 4.16).
Therefore $f$ is not in $\mathcal L^1(\mu, E)$.

  \setlength{\leftskip}{0pt}

\textbf{Exercise 4.15:}

  \setlength{\leftskip}{10pt}

Define $B(f):=\{s: 0\leq s\leq f, s \text{ measurable and simple}\}$.
Since $f\leq g$, $f^+\leq g^+$ and $f^-\geq g^-$.
Then $B(f^+)\subset B(g^+)$, which implies that $\int_Ef^+d\mu\leq\int_Eg^+d\mu$,
and $B(g^-)\subset B(f^-)$, which implies that $\int_Ef^-d\mu\geq\int_Eg^-d\mu$.
Therefore 
\begin{equation*}
\int_Efd\mu=\int_Ef^+d\mu-\int_Ef^-d\mu\leq\int_Eg^+d\mu-\int_Eg^-d\mu=\int_Egd\mu.
\end{equation*}

  \setlength{\leftskip}{0pt}

\textbf{Exercise 4.16:}

  \setlength{\leftskip}{10pt}

Fix an arbitrary measurable simple function $s(x):=\sum_{i=1}^Nc_i\chi_{E_i}$ 
(definition from the lecture notes).
Since $A\subset E$, $\mu(A\cap E_i)\leq\mu(E\cap E_i)$ for each $i$.
Then $\int_Esd\mu:=\sum_{i=1}^Nc_i\mu(A\cap E_i)\leq\sum_{i=1}^Nc_i\mu(E\cap E_i) =\int_Asd\mu$.
Since the choice of $s$ was arbitrary, 
\begin{equation*}
    \int_A||f||d\mu=\sup\left\{\int_Asd\mu: 0\leq s\leq||f||, 
    s \text{ simple}, s \text{ measurable}\right\}
\end{equation*}
is less than or equal to
\begin{equation*}
    \int_E||f||d\mu=\sup\left\{\int_Esd\mu: 0\leq s\leq||f||,
    s \text{ simple}, s \text{ measurable}\right\}.
\end{equation*}

  \setlength{\leftskip}{0pt}

\textbf{Exercise 4.21:}

  \setlength{\leftskip}{10pt}

Define $\lambda_1(A):=\int_Af^+d\mu$ and $\lambda_2(A):=\int_Af^-d\mu$,
then $\int_Afd\mu=\lambda_1(A)-\lambda_2(A)$.
Since $A=(A-B)\cup B$ and $\lambda_i$ is a measure for $i=1,2$ (Theorem 4.6), 
$\lambda_i(A)=\lambda_i(A-B)+\lambda_i(B)$ for $i=1,2$.
However, by Proposition 4.6 we have $\lambda_i(A-B)=0$ for $i=1,2$.
Therefore, $\lambda_i(A)=\lambda_i(B)$ for $i=1,2$.
This implies that $\int_Afd\mu=\lambda_1(B)-\lambda_2(B)=\int_Bfd\mu$,
which implies the result of the corollary.

  \setlength{\leftskip}{0pt}




